function Hd = BPFilter
%TEST Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.1 and the Signal Processing Toolbox 7.3.
% Generated on: 23-Dec-2016 09:53:22

% FIR Window Bandpass filter designed using the FIR1 function.

% All frequency values are in Hz.
Fs = 62500000;  % Sampling Frequency

Fstop1 = 500000;          % First Stopband Frequency
Fpass1 = 1000000;         % First Passband Frequency
Fpass2 = 3000000;         % Second Passband Frequency
Fstop2 = 3500000;         % Second Stopband Frequency
Dstop1 = 0.0001;          % First Stopband Attenuation
Dpass  = 0.057501127785;  % Passband Ripple
Dstop2 = 0.0001;          % Second Stopband Attenuation
flag   = 'noscale';       % Sampling Flag

% Calculate the order from the parameters using KAISERORD.
[N,Wn,BETA,TYPE] = kaiserord([Fstop1 Fpass1 Fpass2 Fstop2]/(Fs/2), [0 1 0], [Dstop1 Dpass Dstop2]);

b  = fir1(N, Wn, TYPE, kaiser(N+1, BETA), flag);
Hd = b;
end

