function sigDEN = func_denoise_dw1d(SIG)
% FUNC_DENOISE_DW1D Saved Denoising Process.
%   SIG: vector of data
%   -------------------
%   sigDEN: vector of denoised data

%  Auto-generated by Wavelet Toolbox on 12-Apr-2018 21:46:48

% Analysis parameters.
%---------------------
wname = 'db4';
level = 5;

% Denoising parameters.
%----------------------
% meth = 'sqtwolog';
% scal_or_alfa = one;
sorh = 'h';    % Specified soft or hard thresholding
thrSettings =  [...
    18.374334715934225 ; ...
    49.212567692278867 ; ...
    54.211731793247139 ; ...
    35.461281782214542 ; ...
    19.778825182826282   ...
    ];

% Denoise using CMDDENOISE.
%--------------------------
sigDEN = cmddenoise(SIG,wname,level,sorh,NaN,thrSettings);
