function sigDEN = waveletDenoise(SIG, wname, thres)
% FUNC_DENOISE_DW1D Saved Denoising Process.
%   SIG: vector of data
%   -------------------
%   sigDEN: vector of denoised data

%  Auto-generated by Wavelet Toolbox on 13-Apr-2018 21:21:13

% Analysis parameters.
%---------------------
%wname = 'sym4';
level = 8;

% Denoising parameters.
%----------------------
% meth = 'sqtwolog';
% scal_or_alfa = one;
%must be s or h
sorh = thres;    % Specified soft or hard thresholding
thrSettings =  [...
    63.548474167277163 ; ...
    42.752747148398356 ; ...
    54.470758369023997 ; ...
    116.869148547342775 ; ...
    85.109591842829786 ; ...
    96.010772283825190 ; ...
    441.397108972691058 ; ...
    326.933042560670401   ...
    ];

% Denoise using CMDDENOISE.
%--------------------------
sigDEN = cmddenoise(SIG,wname,level,sorh,NaN,thrSettings);
